import 'package:vocaboo/utils/leaderboard_listtile.dart';

List<LeaderboardListTile> leaderboard = [
  LeaderboardListTile(
    name: 'Emma Watson',
    lan: 'English',
    stars: 95,
    imgUrl:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJaHDaAiYu3AGk_saOkCaGUMk3q7Pvg7KKIQ&s',
    rank: 1,
  ),
  LeaderboardListTile(
    name: 'Liam Chen',
    lan: 'Spanish',
    stars: 92,
    imgUrl:
        'https://i.pinimg.com/736x/83/9e/0a/839e0a38da17f6ac8bef3ca775d37db2.jpg',
    rank: 2,
  ),
  LeaderboardListTile(
    name: 'Sofia Alvarez',
    lan: 'French',
    stars: 90,
    imgUrl:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSblcAtW4tpbruVT77G9mTIDUGpngs6HvNIfA&s',
    rank: 3,
  ),
  LeaderboardListTile(
    name: 'Noah Müller',
    lan: 'German',
    stars: 88,
    imgUrl: 'https://picsum.photos/200/200?random=4',
    rank: 4,
  ),
  LeaderboardListTile(
    name: 'Ava Zhang',
    lan: 'Chinese',
    stars: 87,
    imgUrl: 'https://picsum.photos/200/200?random=5',
    rank: 5,
  ),
  LeaderboardListTile(
    name: 'Hiroshi Tanaka',
    lan: 'Japanese',
    stars: 85,
    imgUrl: 'https://picsum.photos/200/200?random=6',
    rank: 6,
  ),
  LeaderboardListTile(
    name: 'Isabella Volkov',
    lan: 'Russian',
    stars: 84,
    imgUrl: 'https://picsum.photos/200/200?random=7',
    rank: 7,
  ),
  LeaderboardListTile(
    name: 'Ahmed Hassan',
    lan: 'Arabic',
    stars: 82,
    imgUrl: 'https://picsum.photos/200/200?random=8',
    rank: 8,
  ),
  LeaderboardListTile(
    name: 'Clara Silva',
    lan: 'Portuguese',
    stars: 80,
    imgUrl: 'https://picsum.photos/200/200?random=9',
    rank: 9,
  ),
  LeaderboardListTile(
    name: 'Arjun Sharma',
    lan: 'Hindi',
    stars: 79,
    imgUrl: 'https://picsum.photos/200/200?random=10',
    rank: 10,
  ),
  LeaderboardListTile(
    name: 'Olivia Brown',
    lan: 'English',
    stars: 78,
    imgUrl: 'https://picsum.photos/200/200?random=11',
    rank: 11,
  ),
  LeaderboardListTile(
    name: 'Mateo Garcia',
    lan: 'Spanish',
    stars: 76,
    imgUrl: 'https://picsum.photos/200/200?random=12',
    rank: 12,
  ),
  LeaderboardListTile(
    name: 'Amelia Dubois',
    lan: 'French',
    stars: 75,
    imgUrl: 'https://picsum.photos/200/200?random=13',
    rank: 13,
  ),
  LeaderboardListTile(
    name: 'Lukas Weber',
    lan: 'German',
    stars: 74,
    imgUrl: 'https://picsum.photos/200/200?random=14',
    rank: 14,
  ),
  LeaderboardListTile(
    name: 'Mei Lin',
    lan: 'Chinese',
    stars: 73,
    imgUrl: 'https://picsum.photos/200/200?random=15',
    rank: 15,
  ),
  LeaderboardListTile(
    name: 'Yuki Sato',
    lan: 'Japanese',
    stars: 71,
    imgUrl: 'https://picsum.photos/200/200?random=16',
    rank: 16,
  ),
  LeaderboardListTile(
    name: 'Anastasia Ivanov',
    lan: 'Russian',
    stars: 70,
    imgUrl: 'https://picsum.photos/200/200?random=17',
    rank: 17,
  ),
  LeaderboardListTile(
    name: 'Omar Khalid',
    lan: 'Arabic',
    stars: 69,
    imgUrl: 'https://picsum.photos/200/200?random=18',
    rank: 18,
  ),
  LeaderboardListTile(
    name: 'Beatriz Costa',
    lan: 'Portuguese',
    stars: 68,
    imgUrl: 'https://picsum.photos/200/200?random=19',
    rank: 19,
  ),
  LeaderboardListTile(
    name: 'Rahul Gupta',
    lan: 'Hindi',
    stars: 67,
    imgUrl: 'https://picsum.photos/200/200?random=20',
    rank: 20,
  ),
  LeaderboardListTile(
    name: 'Charlotte Lee',
    lan: 'English',
    stars: 66,
    imgUrl: 'https://picsum.photos/200/200?random=21',
    rank: 21,
  ),
  LeaderboardListTile(
    name: 'Diego Morales',
    lan: 'Spanish',
    stars: 65,
    imgUrl: 'https://picsum.photos/200/200?random=22',
    rank: 22,
  ),
  LeaderboardListTile(
    name: 'Elise Martin',
    lan: 'French',
    stars: 64,
    imgUrl: 'https://picsum.photos/200/200?random=23',
    rank: 23,
  ),
  LeaderboardListTile(
    name: 'Felix Braun',
    lan: 'German',
    stars: 63,
    imgUrl: 'https://picsum.photos/200/200?random=24',
    rank: 24,
  ),
  LeaderboardListTile(
    name: 'Ling Wang',
    lan: 'Chinese',
    stars: 62,
    imgUrl: 'https://picsum.photos/200/200?random=25',
    rank: 25,
  ),
  LeaderboardListTile(
    name: 'Kaito Suzuki',
    lan: 'Japanese',
    stars: 61,
    imgUrl: 'https://picsum.photos/200/200?random=26',
    rank: 26,
  ),
  LeaderboardListTile(
    name: 'Vera Petrova',
    lan: 'Russian',
    stars: 60,
    imgUrl: 'https://picsum.photos/200/200?random=27',
    rank: 27,
  ),
  LeaderboardListTile(
    name: 'Youssef Ali',
    lan: 'Arabic',
    stars: 59,
    imgUrl: 'https://picsum.photos/200/200?random=28',
    rank: 28,
  ),
  LeaderboardListTile(
    name: 'Mariana Lopes',
    lan: 'Portuguese',
    stars: 58,
    imgUrl: 'https://picsum.photos/200/200?random=29',
    rank: 29,
  ),
  LeaderboardListTile(
    name: 'Vikram Singh',
    lan: 'Hindi',
    stars: 57,
    imgUrl: 'https://picsum.photos/200/200?random=30',
    rank: 30,
  ),
  LeaderboardListTile(
    name: 'Grace Taylor',
    lan: 'English',
    stars: 56,
    imgUrl: 'https://picsum.photos/200/200?random=31',
    rank: 31,
  ),
  LeaderboardListTile(
    name: 'Javier Ruiz',
    lan: 'Spanish',
    stars: 55,
    imgUrl: 'https://picsum.photos/200/200?random=32',
    rank: 32,
  ),
  LeaderboardListTile(
    name: 'Camille Leroy',
    lan: 'French',
    stars: 54,
    imgUrl: 'https://picsum.photos/200/200?random=33',
    rank: 33,
  ),
  LeaderboardListTile(
    name: 'Hans Schmidt',
    lan: 'German',
    stars: 53,
    imgUrl: 'https://picsum.photos/200/200?random=34',
    rank: 34,
  ),
  LeaderboardListTile(
    name: 'Xia Liu',
    lan: 'Chinese',
    stars: 52,
    imgUrl: 'https://picsum.photos/200/200?random=35',
    rank: 35,
  ),
  LeaderboardListTile(
    name: 'Ren Yamada',
    lan: 'Japanese',
    stars: 51,
    imgUrl: 'https://picsum.photos/200/200?random=36',
    rank: 36,
  ),
  LeaderboardListTile(
    name: 'Svetlana Moroz',
    lan: 'Russian',
    stars: 50,
    imgUrl: 'https://picsum.photos/200/200?random=37',
    rank: 37,
  ),
  LeaderboardListTile(
    name: 'Khalil Nasser',
    lan: 'Arabic',
    stars: 49,
    imgUrl: 'https://picsum.photos/200/200?random=38',
    rank: 38,
  ),
  LeaderboardListTile(
    name: 'Ana Ribeiro',
    lan: 'Portuguese',
    stars: 48,
    imgUrl: 'https://picsum.photos/200/200?random=39',
    rank: 39,
  ),
  LeaderboardListTile(
    name: 'Rohan Patel',
    lan: 'Hindi',
    stars: 47,
    imgUrl: 'https://picsum.photos/200/200?random=40',
    rank: 40,
  ),
  LeaderboardListTile(
    name: 'Lily Evans',
    lan: 'English',
    stars: 46,
    imgUrl: 'https://picsum.photos/200/200?random=41',
    rank: 41,
  ),
  LeaderboardListTile(
    name: 'Carlos Vega',
    lan: 'Spanish',
    stars: 45,
    imgUrl: 'https://picsum.photos/200/200?random=42',
    rank: 42,
  ),
  LeaderboardListTile(
    name: 'Juliette Blanc',
    lan: 'French',
    stars: 44,
    imgUrl: 'https://picsum.photos/200/200?random=43',
    rank: 43,
  ),
  LeaderboardListTile(
    name: 'Otto Klein',
    lan: 'German',
    stars: 43,
    imgUrl: 'https://picsum.photos/200/200?random=44',
    rank: 44,
  ),
  LeaderboardListTile(
    name: 'Hui Zhao',
    lan: 'Chinese',
    stars: 42,
    imgUrl: 'https://picsum.photos/200/200?random=45',
    rank: 45,
  ),
  LeaderboardListTile(
    name: 'Akira Mori',
    lan: 'Japanese',
    stars: 41,
    imgUrl: 'https://picsum.photos/200/200?random=46',
    rank: 46,
  ),
  LeaderboardListTile(
    name: 'Natasha Romanov',
    lan: 'Russian',
    stars: 40,
    imgUrl: 'https://picsum.photos/200/200?random=47',
    rank: 47,
  ),
  LeaderboardListTile(
    name: 'Zain Abbas',
    lan: 'Arabic',
    stars: 39,
    imgUrl: 'https://picsum.photos/200/200?random=48',
    rank: 48,
  ),
  LeaderboardListTile(
    name: 'Lúcia Santos',
    lan: 'Portuguese',
    stars: 38,
    imgUrl: 'https://picsum.photos/200/200?random=49',
    rank: 49,
  ),
  LeaderboardListTile(
    name: 'Aarav Kumar',
    lan: 'Hindi',
    stars: 37,
    imgUrl: 'https://picsum.photos/200/200?random=50',
    rank: 50,
  ),
];
